stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Auto-DevOps.gitlab-ci.yml
  - remote: "https://gitlab.tapenvy.us/open-source/ci-templates/-/raw/main/ci/auto-tag-release.gitlab-ci.yml"

sast:
  stage: test

staging:
  dependencies:
    - build
  stage: staging
  script:
    - echo $DB_HOST > ansible/templates/database_host
    - echo $DB_NAME > ansible/templates/database_name
    - echo $DB_PASSWORD > ansible/templates/database_password
    - echo $DB_USER > ansible/templates/database_username
    - echo $CI_REGISTRY_USER > ansible/templates/username
    - echo $CI_REGISTRY_PASSWORD > ansible/templates/password
    - echo $SENDGRID_API_KEY > ansible/templates/sendgrid
    - ansible-playbook ansible/staging.yml
  environment:
    name: staging
    url: https://battletech.dev
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  tags:
    - deploy

tag_release:
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"

production:
  dependencies:
    - build
  stage: production
  script:
    - echo $DATABASE_HOST > ansible/templates/database_host
    - echo $DATABASE_NAME > ansible/templates/database_name
    - echo $DATABASE_PASSWORD > ansible/templates/database_password
    - echo $DATABASE_USER > ansible/templates/database_username
    - echo $CI_REGISTRY_USER > ansible/templates/username
    - echo $CI_REGISTRY_PASSWORD > ansible/templates/password
    - echo $SENDGRID_API_KEY > ansible/templates/sendgrid
    - ansible-playbook ansible/production.yml
  environment:
    name: production
    url: https://quatermaster-command.services
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"
      when: manual
  tags:
    - deploy
