default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: qcs
  username: qcs
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  port: 5432

test:
  <<: *default
  port: 5433
